// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ48_W3df562VB7biRhpxQ5rBUa--JvBM',
    appId: '1:311387946445:web:4f5f3f024080d31068d884',
    messagingSenderId: '311387946445',
    projectId: 'weefo-39139',
    authDomain: 'weefo-39139.firebaseapp.com',
    databaseURL: 'https://weefo-39139-default-rtdb.firebaseio.com',
    storageBucket: 'weefo-39139.appspot.com',
    measurementId: 'G-5JCQPLBSBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1qbcvmWWfrU4kfJyC2E0w-NTDcf3hCZc',
    appId: '1:311387946445:android:1bd37565e3e9fa4468d884',
    messagingSenderId: '311387946445',
    projectId: 'weefo-39139',
    databaseURL: 'https://weefo-39139-default-rtdb.firebaseio.com',
    storageBucket: 'weefo-39139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGQPJDo_rqp0Cuj6whU2QCk3Vh08Y5EM',
    appId: '1:311387946445:ios:b93f43a201d073c468d884',
    messagingSenderId: '311387946445',
    projectId: 'weefo-39139',
    databaseURL: 'https://weefo-39139-default-rtdb.firebaseio.com',
    storageBucket: 'weefo-39139.appspot.com',
    iosBundleId: 'com.example.automobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGQPJDo_rqp0Cuj6whU2QCk3Vh08Y5EM',
    appId: '1:311387946445:ios:325adde13e47c90a68d884',
    messagingSenderId: '311387946445',
    projectId: 'weefo-39139',
    databaseURL: 'https://weefo-39139-default-rtdb.firebaseio.com',
    storageBucket: 'weefo-39139.appspot.com',
    iosBundleId: 'com.example.automobile.RunnerTests',
  );
}
